I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 278, in script
    python:
  File "renpy/common/00start.rpy", line 278, in script
    python:
  File "renpy/common/00start.rpy", line 282, in <module>
    renpy.call_in_new_context("_main_menu")
OSError: Couldn't find file 'sys_void.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\main.py", line 660, in main
    run(restart)
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\main.py", line 146, in run
    renpy.execution.run_context(True)
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 278, in script
    python:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "renpy/common/00start.rpy", line 278, in script
    python:
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 282, in <module>
    renpy.call_in_new_context("_main_menu")
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\game.py", line 346, in call_in_new_context
    return renpy.execution.run_context(False)
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\display\core.py", line 4103, in interact_core
    renpy.audio.audio.periodic()
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\audio\audio.py", line 1166, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\audio\audio.py", line 1144, in periodic_thread_main
    periodic_pass()
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\audio\audio.py", line 1086, in periodic_pass
    c.periodic()
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\audio\audio.py", line 517, in periodic
    topf = load(filename)
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\audio\audio.py", line 70, in load
    rv = renpy.loader.load(fn)
  File "F:\Program Files (x86)\Renpy\renpy-7.4.11-sdk\renpy\loader.py", line 820, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'sys_void.mp3'.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
龙门轶事 0.15
Wed Jan 11 18:57:42 2023
